name: Nightly
on:
  schedule:
    - cron: 0 8 * * 0-6
  workflow_dispatch: {}

jobs:
  trunk_check:
    name: Trunk Check Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          trunk-token: ${{ secrets.CLIENT_TRUNK_TOKEN }}